-- Remove implicit indexes superseded by the named Phase 1 indexes.
-- These indexes were generated by SQLAlchemy column-level index=True before
-- the models adopted the explicit idx_* definitions in __table_args__.

DROP INDEX IF EXISTS ix_game_broadcasts_game_id;
DROP INDEX IF EXISTS ix_cheer_songs_team_id;
DROP INDEX IF EXISTS ix_cheer_chants_team_id;
DROP INDEX IF EXISTS ix_foreign_player_changes_team_id;
DROP INDEX IF EXISTS ix_foreign_player_changes_player_id;
DROP INDEX IF EXISTS ix_game_mvps_game_id;
DROP INDEX IF EXISTS ix_game_mvps_player_id;
DROP INDEX IF EXISTS ix_injury_entries_team_id;
DROP INDEX IF EXISTS ix_injury_entries_player_id;
DROP INDEX IF EXISTS ix_manager_changes_team_id;
