"""Standard Data Transfer Objects (DTOs) for Unified Configuration Management."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class EnvironmentType(StrEnum):
    """Platform deployment environments."""

    LOCAL = "local"
    DEVELOPMENT = "development"
    STAGING = "staging"
    PRODUCTION = "production"
    CI = "ci"


@dataclass
class DatabaseConfig:
    """Database connection and pooling parameters."""

    url: str
    dialect: str = "sqlite"
    tns_admin: str | None = None
    pool_size: int = 5
    max_overflow: int = 10
    echo: bool = False

    def to_dict(self, *, mask: bool = False) -> dict[str, Any]:
        """Convert database configuration to dictionary with optional secret masking."""
        display_url = self.url
        if mask and ("@" in self.url):
            # Mask password in connection URI
            parts = self.url.split("@")
            prefix = parts[0].split("://")[0]
            display_url = f"{prefix}://***@{parts[1]}"
        return {
            "url": display_url,
            "dialect": self.dialect,
            "tns_admin": self.tns_admin,
            "pool_size": self.pool_size,
            "max_overflow": self.max_overflow,
            "echo": self.echo,
        }


@dataclass
class CrawlerConfig:
    """Crawler throttling, browser settings, and concurrency parameters."""

    delay_min_seconds: float = 1.0
    delay_max_seconds: float = 3.0
    headless: bool = True
    timeout_seconds: int = 30
    concurrency: int = 3

    def to_dict(self) -> dict[str, Any]:
        """Convert crawler configuration to dictionary."""
        return {
            "delay_min_seconds": self.delay_min_seconds,
            "delay_max_seconds": self.delay_max_seconds,
            "headless": self.headless,
            "timeout_seconds": self.timeout_seconds,
            "concurrency": self.concurrency,
        }


@dataclass
class AlertingConfig:
    """Notification credentials and webhook endpoints."""

    telegram_bot_token: str | None = None
    telegram_chat_id: str | None = None
    slack_webhook_url: str | None = None
    alert_threshold: int = 5

    def to_dict(self, *, mask: bool = False) -> dict[str, Any]:
        """Convert alerting configuration to dictionary with optional masking."""
        return {
            "telegram_bot_token": "***" if (mask and self.telegram_bot_token) else self.telegram_bot_token,
            "telegram_chat_id": self.telegram_chat_id,
            "slack_webhook_url": "***" if (mask and self.slack_webhook_url) else self.slack_webhook_url,
            "alert_threshold": self.alert_threshold,
        }


@dataclass
class ExternalApiConfig:
    """Third-party service credentials (YouTube, Naver)."""

    youtube_api_key: str | None = None
    naver_client_id: str | None = None
    naver_client_secret: str | None = None

    def to_dict(self, *, mask: bool = False) -> dict[str, Any]:
        """Convert external API credentials to dictionary with optional masking."""
        return {
            "youtube_api_key": "***" if (mask and self.youtube_api_key) else self.youtube_api_key,
            "naver_client_id": self.naver_client_id,
            "naver_client_secret": "***" if (mask and self.naver_client_secret) else self.naver_client_secret,
        }


@dataclass
class PlatformSettings:
    """Unified application configuration root."""

    env: EnvironmentType = EnvironmentType.LOCAL
    debug: bool = False
    database: DatabaseConfig = field(default_factory=lambda: DatabaseConfig(url="sqlite:///./data/kbo_dev.db"))
    crawler: CrawlerConfig = field(default_factory=CrawlerConfig)
    alerting: AlertingConfig = field(default_factory=AlertingConfig)
    external_api: ExternalApiConfig = field(default_factory=ExternalApiConfig)
    feature_flags: dict[str, bool] = field(default_factory=dict)

    def to_dict(self, *, mask: bool = True) -> dict[str, Any]:
        """Convert settings to dictionary with secrets masked."""
        return {
            "env": self.env.value,
            "debug": self.debug,
            "database": self.database.to_dict(mask=mask),
            "crawler": self.crawler.to_dict(),
            "alerting": self.alerting.to_dict(mask=mask),
            "external_api": self.external_api.to_dict(mask=mask),
            "feature_flags": self.feature_flags,
        }


@dataclass
class ConfigValidationReport:
    """Report generated by environment validator."""

    is_valid: bool
    missing_required_keys: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    checked_at: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Convert validation report to dictionary."""
        return {
            "is_valid": self.is_valid,
            "missing_required_keys": self.missing_required_keys,
            "warnings": self.warnings,
            "checked_at": self.checked_at,
        }
