-- Oracle-only bootstrap for the ORM-owned CRAWL_RUNS table.
--
-- CrawlRun is created by SQLAlchemy metadata bootstrap and has no source
-- migration under migrations/oci/. Keep this table bootstrap separate from
-- 042, which only adds its uniqueness index.
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_tables
     WHERE table_name = 'CRAWL_RUNS';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE CRAWL_RUNS (
                ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                LABEL VARCHAR2(128),
                STARTED_AT TIMESTAMP NOT NULL,
                FINISHED_AT TIMESTAMP NOT NULL,
                ACTIVE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
                RETIRED_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
                STAFF_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
                CONFIRMED_PROFILES NUMBER(10) DEFAULT 0 NOT NULL,
                HEURISTIC_ONLY NUMBER(10) DEFAULT 0 NOT NULL,
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                CONSTRAINT PK_CRAWL_RUNS PRIMARY KEY (ID)
            )
        ]';
    END IF;
END;
/
