-- Oracle-only bootstrap for the ORM-owned TEAM_DAILY_ROSTER table.
--
-- This table is created by SQLAlchemy Base.metadata.create_all() in the
-- application bootstrap and has no source file under migrations/oci/. The
-- existing OCI schema predates that bootstrap, so keep this as a separate,
-- idempotent Oracle migration before the 024 integrity work.
DECLARE
    v_exists NUMBER;

    PROCEDURE create_table_if_missing(p_table_name VARCHAR2, p_ddl VARCHAR2) IS
    BEGIN
        SELECT COUNT(*)
          INTO v_exists
          FROM user_tables
         WHERE table_name = UPPER(p_table_name);
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;
BEGIN
    create_table_if_missing('TEAM_DAILY_ROSTER', q'[
        CREATE TABLE TEAM_DAILY_ROSTER (
            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            ROSTER_DATE DATE NOT NULL,
            TEAM_CODE VARCHAR2(10) NOT NULL,
            PLAYER_ID NUMBER(10) NOT NULL,
            PLAYER_BASIC_ID NUMBER(10),
            PERSON_TYPE VARCHAR2(16) DEFAULT 'player' NOT NULL,
            PLAYER_NAME VARCHAR2(50) NOT NULL,
            POSITION VARCHAR2(20),
            BACK_NUMBER VARCHAR2(10),
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT PK_TEAM_DAILY_ROSTER PRIMARY KEY (ID),
            CONSTRAINT UQ_TEAM_DAILY_ROSTER
                UNIQUE (ROSTER_DATE, TEAM_CODE, PLAYER_ID),
            CONSTRAINT FK_TEAM_DAILY_ROSTER_TEAM
                FOREIGN KEY (TEAM_CODE) REFERENCES TEAMS (TEAM_ID),
            CONSTRAINT FK_TEAM_DAILY_ROSTER_PLAYER
                FOREIGN KEY (PLAYER_BASIC_ID) REFERENCES PLAYER_BASIC (PLAYER_ID)
        )
    ]');
END;
/

DECLARE
    v_exists NUMBER;

    PROCEDURE create_index_if_missing(p_index_name VARCHAR2, p_ddl VARCHAR2) IS
    BEGIN
        SELECT COUNT(*)
          INTO v_exists
          FROM user_indexes
         WHERE index_name = UPPER(p_index_name);
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;
BEGIN
    create_index_if_missing(
        'IDX_TEAM_DAILY_ROSTER_DATE',
        'CREATE INDEX IDX_TEAM_DAILY_ROSTER_DATE ON TEAM_DAILY_ROSTER (ROSTER_DATE)'
    );
    create_index_if_missing(
        'IDX_TEAM_DAILY_ROSTER_TEAM',
        'CREATE INDEX IDX_TEAM_DAILY_ROSTER_TEAM ON TEAM_DAILY_ROSTER (TEAM_CODE)'
    );
    create_index_if_missing(
        'IDX_TEAM_DAILY_ROSTER_PLAYER_BASIC',
        'CREATE INDEX IDX_TEAM_DAILY_ROSTER_PLAYER_BASIC '
        || 'ON TEAM_DAILY_ROSTER (PLAYER_BASIC_ID)'
    );
END;
/
