-- Oracle port of 046_add_team_stats_extended_fields.sql.
DECLARE
    v_exists NUMBER;

    PROCEDURE add_column_if_missing(p_table_name VARCHAR2, p_column_name VARCHAR2, p_ddl VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO v_exists
          FROM user_tab_columns
         WHERE table_name = UPPER(p_table_name)
           AND column_name = UPPER(p_column_name);
        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;
BEGIN
    add_column_if_missing('TEAM_SEASON_BATTING', 'INTENTIONAL_WALKS', 'ALTER TABLE TEAM_SEASON_BATTING ADD (INTENTIONAL_WALKS NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_BATTING', 'HBP', 'ALTER TABLE TEAM_SEASON_BATTING ADD (HBP NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_BATTING', 'SACRIFICE_HITS', 'ALTER TABLE TEAM_SEASON_BATTING ADD (SACRIFICE_HITS NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_BATTING', 'SACRIFICE_FLIES', 'ALTER TABLE TEAM_SEASON_BATTING ADD (SACRIFICE_FLIES NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_BATTING', 'GDP', 'ALTER TABLE TEAM_SEASON_BATTING ADD (GDP NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_BATTING', 'ISO', 'ALTER TABLE TEAM_SEASON_BATTING ADD (ISO FLOAT)');
    add_column_if_missing('TEAM_SEASON_BATTING', 'BABIP', 'ALTER TABLE TEAM_SEASON_BATTING ADD (BABIP FLOAT)');

    add_column_if_missing('TEAM_SEASON_PITCHING', 'INNINGS_OUTS', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (INNINGS_OUTS NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'INTENTIONAL_WALKS', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (INTENTIONAL_WALKS NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'HIT_BATTERS', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (HIT_BATTERS NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'TBF', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (TBF NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'COMPLETE_GAMES', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (COMPLETE_GAMES NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'SHUTOUTS', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (SHUTOUTS NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'WILD_PITCHES', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (WILD_PITCHES NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'BALKS', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (BALKS NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'SACRIFICES_ALLOWED', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (SACRIFICES_ALLOWED NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'SACRIFICE_FLIES_ALLOWED', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (SACRIFICE_FLIES_ALLOWED NUMBER(10))');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'K_PER_NINE', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (K_PER_NINE FLOAT)');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'BB_PER_NINE', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (BB_PER_NINE FLOAT)');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'KBB', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (KBB FLOAT)');
    add_column_if_missing('TEAM_SEASON_PITCHING', 'FIP', 'ALTER TABLE TEAM_SEASON_PITCHING ADD (FIP FLOAT)');
END;
/
