-- Recompute hashes for rows loaded while the hash trigger was disabled.
BEGIN
    UPDATE GAME_SUMMARY
       SET DETAIL_TEXT_HASH = CASE
           WHEN DETAIL_TEXT IS NULL THEN 'D41D8CD98F00B204E9800998ECF8427E'
           ELSE RAWTOHEX(DBMS_CRYPTO.HASH(DETAIL_TEXT, DBMS_CRYPTO.HASH_MD5))
       END
     WHERE DETAIL_TEXT_HASH IS NULL;
END;
/
