-- Durable incident ledger for the in-process notification alert manager.
-- Idempotent: safe when SQLAlchemy create_all already created the ORM table.
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_tables
     WHERE table_name = 'NOTIFICATION_INCIDENTS';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE NOTIFICATION_INCIDENTS ('
            || 'ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, '
            || 'INCIDENT_KEY VARCHAR2(255 CHAR) NOT NULL, '
            || 'SOURCE VARCHAR2(64 CHAR) NOT NULL, '
            || 'COMPONENT VARCHAR2(128 CHAR) DEFAULT '' '' NOT NULL, '
            || 'SEVERITY VARCHAR2(16 CHAR) NOT NULL, '
            || 'STATE VARCHAR2(16 CHAR) DEFAULT ''OPEN'' NOT NULL, '
            || 'TITLE VARCHAR2(255 CHAR) DEFAULT '' '' NOT NULL, '
            || 'MESSAGE CLOB DEFAULT '' '' NOT NULL, '
            || 'DETAILS_HASH VARCHAR2(64 CHAR) DEFAULT '' '' NOT NULL, '
            || 'OCCURRENCE_COUNT NUMBER(10) DEFAULT 1 NOT NULL, '
            || 'NOTIFICATION_COUNT NUMBER(10) DEFAULT 0 NOT NULL, '
            || 'FIRST_OPENED_AT TIMESTAMP NOT NULL, '
            || 'LAST_SEEN_AT TIMESTAMP NOT NULL, '
            || 'LAST_NOTIFIED_AT TIMESTAMP, '
            || 'RESOLVED_AT TIMESTAMP, '
            || 'METADATA CLOB, '
            || 'CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, '
            || 'UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, '
            || 'CONSTRAINT UQ_NOTIFICATION_INCIDENTS_KEY UNIQUE (INCIDENT_KEY), '
            || 'CONSTRAINT PK_NOTIFICATION_INCIDENTS PRIMARY KEY (ID))';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_indexes
     WHERE index_name = 'IDX_NOTIFICATION_INCIDENTS_STATE_SEV';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_NOTIFICATION_INCIDENTS_STATE_SEV '
            || 'ON NOTIFICATION_INCIDENTS (STATE, SEVERITY)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_indexes
     WHERE index_name = 'IDX_NOTIFICATION_INCIDENTS_SRC_SEEN';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_NOTIFICATION_INCIDENTS_SRC_SEEN '
            || 'ON NOTIFICATION_INCIDENTS (SOURCE, LAST_SEEN_AT)';
    END IF;
END;
/
