-- Append-only delivery audit ledger for the notification subsystem.
-- `INCIDENT_ID` is a soft reference (no FK constraint) so incident retention and
-- delivery retention stay independent. Idempotent: safe when SQLAlchemy
-- create_all already created the ORM table.
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_tables
     WHERE table_name = 'NOTIFICATION_DELIVERIES';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE NOTIFICATION_DELIVERIES ('
            || 'ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, '
            || 'INCIDENT_ID NUMBER(19), '
            || 'NOTIFICATION_TYPE VARCHAR2(32 CHAR) DEFAULT ''notification'' NOT NULL, '
            || 'BATCH_ID VARCHAR2(36 CHAR) DEFAULT '' '' NOT NULL, '
            || 'CHANNEL VARCHAR2(32 CHAR) NOT NULL, '
            || 'DESTINATION VARCHAR2(255 CHAR), '
            || 'STATUS VARCHAR2(32 CHAR) NOT NULL, '
            || 'ATTEMPT_COUNT NUMBER(10) DEFAULT 1 NOT NULL, '
            || 'DISPATCHED_AT TIMESTAMP NOT NULL, '
            || 'COMPLETED_AT TIMESTAMP, '
            || 'LATENCY_MS NUMBER(19), '
            || 'ERROR_CODE VARCHAR2(64 CHAR), '
            || 'ERROR_MESSAGE CLOB, '
            || 'CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, '
            || 'UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, '
            || 'CONSTRAINT PK_NOTIFICATION_DELIVERIES PRIMARY KEY (ID))';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_indexes
     WHERE index_name = 'IDX_NOTIFICATION_DELIVERIES_INCIDENT';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_NOTIFICATION_DELIVERIES_INCIDENT '
            || 'ON NOTIFICATION_DELIVERIES (INCIDENT_ID, DISPATCHED_AT)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_indexes
     WHERE index_name = 'IDX_NOTIFICATION_DELIVERIES_CHAN_STATUS';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_NOTIFICATION_DELIVERIES_CHAN_STATUS '
            || 'ON NOTIFICATION_DELIVERIES (CHANNEL, STATUS, DISPATCHED_AT)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_indexes
     WHERE index_name = 'IDX_NOTIFICATION_DELIVERIES_BATCH';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_NOTIFICATION_DELIVERIES_BATCH '
            || 'ON NOTIFICATION_DELIVERIES (BATCH_ID)';
    END IF;
END;
/
