-- Fee kinds printed on stadium parking pages (기본/추가/일일/행사/경기/무료).
-- `parking_fee_rules` is keyed by vehicle class, so these kinds never had a
-- table of their own; they lived only in the raw snapshot text.
-- Idempotent: safe when SQLAlchemy create_all already created the ORM table.
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_tables
     WHERE table_name = 'PARKING_FEE_KINDS';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE PARKING_FEE_KINDS ('
            || 'ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, '
            || 'PARKING_LOT_ID NUMBER(10) NOT NULL, '
            || 'FEE_KIND VARCHAR2(16 CHAR) NOT NULL, '
            || 'AMOUNT_KRW NUMBER(10) NOT NULL, '
            || 'SOURCE_URL VARCHAR2(500 CHAR), '
            || 'CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, '
            || 'UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, '
            || 'CONSTRAINT UQ_PARKING_FEE_KIND UNIQUE (PARKING_LOT_ID, FEE_KIND), '
            || 'CONSTRAINT PK_PARKING_FEE_KINDS PRIMARY KEY (ID))';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_indexes
     WHERE index_name = 'IDX_PARKING_FEE_KINDS_LOT';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_PARKING_FEE_KINDS_LOT '
            || 'ON PARKING_FEE_KINDS (PARKING_LOT_ID)';
    END IF;
END;
/
