-- 079_stadiums_places.sql
-- Requested master tables: STADIUMS and PLACES. Mirrors the production
-- table shapes. Idempotent via user_tables/user_indexes guards (safe when
-- SQLAlchemy created them).
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_tables
     WHERE table_name = 'STADIUMS';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE STADIUMS ('
            || 'STADIUM_ID VARCHAR2(10 CHAR), '
            || 'STADIUM_NAME VARCHAR2(100 CHAR), '
            || 'CITY VARCHAR2(100 CHAR), '
            || 'TEAM VARCHAR2(20 CHAR), '
            || 'CAPACITY NUMBER(10), '
            || 'SEATING_CAPACITY NUMBER(10), '
            || 'OPEN_YEAR NUMBER(10), '
            || 'LEFT_FENCE_M NUMBER, '
            || 'CENTER_FENCE_M NUMBER, '
            || 'FENCE_HEIGHT_M NUMBER, '
            || 'TURF_TYPE VARCHAR2(20 CHAR), '
            || 'BULLPEN_TYPE VARCHAR2(20 CHAR), '
            || 'HOMERUN_PARK_FACTOR NUMBER, '
            || 'NOTES VARCHAR2(500 CHAR), '
            || 'LAT NUMBER, '
            || 'LNG NUMBER, '
            || 'ADDRESS VARCHAR2(300 CHAR), '
            || 'PHONE VARCHAR2(30 CHAR), '
            || 'CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, '
            || 'UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, '
            || 'CONSTRAINT PK_STADIUMS PRIMARY KEY (STADIUM_ID))';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_tables
     WHERE table_name = 'PLACES';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE PLACES ('
            || 'ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, '
            || 'STADIUM_ID VARCHAR2(10 CHAR) NOT NULL, '
            || 'CATEGORY VARCHAR2(20 CHAR) NOT NULL, '
            || 'NAME VARCHAR2(100 CHAR) NOT NULL, '
            || 'DESCRIPTION VARCHAR2(500 CHAR), '
            || 'LAT NUMBER NOT NULL, '
            || 'LNG NUMBER NOT NULL, '
            || 'ADDRESS VARCHAR2(300 CHAR), '
            || 'PHONE VARCHAR2(30 CHAR), '
            || 'RATING NUMBER, '
            || 'OPEN_TIME VARCHAR2(50 CHAR), '
            || 'CLOSE_TIME VARCHAR2(50 CHAR), '
            || 'CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, '
            || 'UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, '
            || 'CONSTRAINT PK_PLACES PRIMARY KEY (ID), '
            || 'CONSTRAINT FK_PLACES_STADIUM FOREIGN KEY (STADIUM_ID) '
            || 'REFERENCES STADIUMS (STADIUM_ID) ON DELETE CASCADE)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_indexes
     WHERE index_name = 'IDX_PLACES_STADIUM';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_PLACES_STADIUM ON PLACES (STADIUM_ID)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM user_indexes
     WHERE index_name = 'IDX_PLACES_CATEGORY';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IDX_PLACES_CATEGORY ON PLACES (CATEGORY)';
    END IF;
END;
/
