"""Scoped mypy gate for certified-clean modules.

Runs mypy over an explicit allowlist of modules that have been verified to
produce zero attributed errors, and fails when any error is attributed to a
listed file. Errors in transitive dependencies are ignored here; they belong
to future cleanup batches.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# Modules certified to produce zero mypy errors attributed to themselves.
# Add new files only after verifying `mypy <file>` reports no errors for them.
SCOPED_FILES: tuple[str, ...] = (
    "scripts/maintenance/fix_relay_state.py",
    "src/__init__.py",
    "src/analytics/matchup.py",
    "src/api/app.py",
    "src/api/auth.py",
    "src/api/routers/games.py",
    "src/api/routers/pipeline.py",
    "src/aggregators/team_stat_aggregator.py",
    "src/analytics/predictor.py",
    "src/analytics/sabermetrics.py",
    "src/cli/backfill/auto_healer.py",
    "src/cli/backfill/fix_player_names.py",
    "src/cli/backfill/backfill_advanced_stats.py",
    "src/api/routers/health.py",
    "src/api/routers/stadiums.py",
    "src/api/schemas.py",
    "src/certification/models.py",
    "src/crawlers/award_crawler.py",
    "src/crawlers/retire/detail.py",
    "src/crawlers/transit_time_crawler.py",
    "src/sources/relay/orchestrator.py",
    "src/sources/relay/relay_deduplicator.py",
    "src/sources/stats/fangraphs.py",
    "src/cli/backfill/regenerate_review_summaries.py",
    "src/cli/calc/calculate_projections.py",
    "src/cli/calc/recalc_player_stats.py",
    "src/cli/collection/ingest_historical_season.py",
    "src/cli/kbo.py",
    "src/certification/registry.py",
    "src/cli/collection/collect_profiles.py",
    "src/cli/collection/crawl_futures.py",
    "src/cli/collection/crawl_retire.py",
    "src/cli/collection/ingest_historical_archive.py",
    "src/cli/live/dashboard.py",
    "src/cli/analyze_data.py",
    "src/cli/api_server.py",
    "src/cli/build_rag_index.py",
    "src/cli/check_data_status.py",
    "src/cli/collect_games.py",
    "src/cli/crawl_awards.py",
    "src/cli/crawl_congestion.py",
    "src/cli/crawl_futures_schedule.py",
    "src/cli/crawl_legacy_reviews.py",
    "src/cli/crawl_milestones.py",
    "src/cli/crawl_operation_notices.py",
    "src/cli/crawl_parking.py",
    "src/cli/crawl_player_drafts.py",
    "src/cli/crawl_player_splits.py",
    "src/cli/crawl_press_releases.py",
    "src/cli/crawl_retire.py",
    "src/cli/crawl_roster_transactions.py",
    "src/cli/crawl_schedule.py",
    "src/cli/crawl_seat_sections.py",
    "src/cli/crawl_stadium_food.py",
    "src/cli/crawl_staff_register.py",
    "src/cli/crawl_team_events.py",
    "src/cli/crawl_ticket_info.py",
    "src/cli/crawl_transit_time.py",
    "src/cli/data_integrity_checker.py",
    "src/cli/db_healthcheck.py",
    "src/cli/gap_report.py",
    "src/cli/generate_game_preview.py",
    "src/cli/health_check.py",
    "src/cli/index_rag_knowledge.py",
    "src/cli/ingest_mock_game_html.py",
    "src/cli/run_pgvector_migration.py",
    "src/cli/seed_p1_data.py",
    "src/cli/lookup_official_players.py",
    "src/cli/monitor_data_freshness.py",
    "src/cli/pipelines/run_pipeline_demo.py",
    "src/cli/query_rag_knowledge.py",
    "src/cli/rag/apply_rag_rekey.py",
    "src/cli/rag/audit_rag_index.py",
    "src/cli/rag/reconcile_rag_stores.py",
    "src/cli/ingest_schedule_html.py",
    "src/cli/rag/build_oracle_sparse_index.py",
    "src/cli/rag/census_rag_identity.py",
    "src/cli/rag/propagate_rag_index.py",
    "src/cli/recalc_milestones.py",
    "src/cli/repair_game_stats.py",
    "src/cli/reports/compare_crawl_evidence.py",
    "src/cli/run_api_server.py",
    "src/cli/run_pipeline_demo.py",
    "src/cli/seed_data_sources.py",
    "src/cli/send_milestone_daily_summary.py",
    "src/cli/send_postgame_wpa_alerts.py",
    "src/cli/send_pregame_alerts.py",
    "src/cli/send_today_pregame_alerts.py",
    "src/cli/smart_polling_gate.py",
    "src/cli/pipelines/pipeline_dashboard.py",
    "src/cli/pipelines/run_daily_update.py",
    "src/cli/pipelines/run_weekly_maintenance.py",
    "src/cli/pipelines/run_advanced_daily.py",
    "src/cli/rag/repair_season_year_metadata.py",
    "src/cli/reports/audit_awards.py",
    "src/cli/reports/dashboard_report.py",
    "src/cli/reports/historical_coverage_report.py",
    "src/cli/reports/monitor_data_freshness.py",
    "src/cli/reports/quality_dashboard.py",
    "src/cli/reports/data_integrity_checker.py",
    "src/cli/reports/gap_report.py",
    "src/cli/sync/run_pgvector_migration.py",
    "src/cli/sync/apply_oracle_migrations.py",
    "src/cli/sync/stage_official_season_stats.py",
    "src/crawlers/circuit_breaker.py",
    "src/crawlers/draft_history_crawler.py",
    "src/crawlers/futures_schedule_crawler.py",
    "src/crawlers/game_detail_crawler.py",
    "src/crawlers/legacy_game_detail_crawler.py",
    "src/crawlers/milestone_crawler.py",
    "src/crawlers/player_splits_crawler.py",
    "src/crawlers/team_batting_stats_crawler.py",
    "src/crawlers/team_pitching_stats_crawler.py",
    "src/crawlers/registry.py",
    "src/crawlers/historical_season_crawler.py",
    "src/cli/rag/build_rag_index.py",
    "src/cli/rag/evaluate_rag_retrieval.py",
    "src/rag/indexer/knowledge_indexer.py",
    "src/rag/retrievers/hybrid.py",
    "src/reporting/scouting_engine.py",
    "src/crawlers/base.py",
    "src/db/drift_detector.py",
    "src/db/engine.py",
    "src/db/types.py",
    "src/models/dto.py",
    "src/models/game.py",
    "src/models/inspector.py",
    "src/models/player.py",
    "src/models/season.py",
    "src/models/team.py",
    "src/orchestration/master.py",
    "src/scheduler/jobs/daily.py",
    "src/scheduler/jobs/live.py",
    "src/scheduler/jobs/stadium.py",
    "src/scheduler/locks.py",
    "src/scheduler/jobs/maintenance.py",
    "src/services/rag_index_consistency.py",
    "src/services/award_snapshot_lifecycle.py",
    "src/services/award_source_audit.py",
    "src/pipeline/auto_healer_service.py",
    "src/pipeline/defect_detector.py",
    "src/services/multi_source_reconciler.py",
    "src/simulation/live_stream_processor.py",
    "src/services/rag_corpus_inventory.py",
    "src/services/historical_boxscore_ingestor.py",
    "src/services/historical_detail_backfill_service.py",
    "src/services/hybrid_retriever.py",
    "src/services/rag_index_propagation.py",
    "src/db/vector_engine.py",
    "src/formulas/engine.py",
    "src/monitoring/crawl_gate.py",
    "src/monitoring/selector_drift_sentinel.py",
    "src/parsers/base_parser.py",
    "src/parsers/player_profile_parser.py",
    "src/parsers/retired_player_parser.py",
    "src/rag/retrievers/oracle_dense.py",
    "src/services/rag_reconciliation.py",
    "src/services/rag_search_engine.py",
    "src/services/rag_sparse_terms.py",
    "src/scheduler/registry.py",
    "src/repositories/oracle_sparse_search_repository.py",
    "src/services/staging_rollback.py",
    "src/services/rag_service.py",
    "src/services/rag_identity_census.py",
    "src/services/quarantine_service.py",
    "src/services/notification_service.py",
    "src/sync/cdc_daemon.py",
    "src/sync/oracle_writer.py",
    "src/cli/sync/sync_sqlite_to_oci.py",
    "src/services/relay_recovery_engine.py",
    "src/services/staging_canary.py",
    "src/services/wpa_chart_service.py",
    "src/testing/synthetic_generator.py",
    "src/utils/lock.py",
    "src/utils/playwright_pool.py",
    "src/utils/url_validator.py",
    "src/validators/lineup_rules.py",
    "src/validators/quality_gate.py",
    "src/validators/season_team_code.py",
    "scripts/maintenance/audit_pa_formula.py",
    "scripts/maintenance/resolve_null_player_ids_conservative.py",
    "src/analytics/similarity.py",
    "src/certification/gates/schema.py",
    "src/certification/gates/vector_rag.py",
    "src/ci/verifier.py",
    "src/cli/backfill/backfill_pregame_previews.py",
    "src/cli/backfill/regenerate_game_stories.py",
    "src/cli/backfill/retry_daily_failures.py",
    "src/cli/calc/monthly_unified_audit.py",
    "src/cli/collection/crawl_external_stats.py",
    "src/cli/crawl_futures.py",
    "src/cli/crawl_p0_data.py",
    "src/services/historical_1982_pilot_service.py",
    "src/sync/sync_engine.py",
)


def main() -> int:
    """Run mypy on scoped files and fail on any attributed error."""
    repo_root = Path(__file__).resolve().parents[1]
    missing = [f for f in SCOPED_FILES if not (repo_root / f).exists()]
    if missing:
        sys.stderr.write(f"scoped mypy gate: listed files missing: {missing}\n")
        return 2
    proc = subprocess.run(
        [sys.executable, "-m", "mypy", *SCOPED_FILES],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=False,
    )
    output = (proc.stdout or "") + (proc.stderr or "")
    attributed = [line for line in output.splitlines() if line.startswith(SCOPED_FILES) and "error:" in line]
    if attributed:
        sys.stdout.write("\n".join(attributed) + "\n")
        sys.stdout.write(f"scoped mypy gate: {len(attributed)} error(s) in certified files\n")
        return 1
    sys.stdout.write(f"scoped mypy gate: {len(SCOPED_FILES)} files clean\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
