-- 041_create_player_game_tables.sql
-- OCI migration: Player-game-level batting and pitching aggregation tables.

CREATE TABLE IF NOT EXISTS player_game_batting (
    id                   SERIAL       PRIMARY KEY,
    game_id              VARCHAR(20)  NOT NULL REFERENCES game(game_id) ON DELETE CASCADE,
    player_id            INTEGER      NOT NULL REFERENCES player_basic(player_id) ON DELETE RESTRICT,
    player_name          VARCHAR(64)  NOT NULL,
    team_side            VARCHAR(5)   NOT NULL,
    team_code            VARCHAR(10),
    batting_order        INTEGER,
    appearance_seq       INTEGER,
    position             VARCHAR(8),
    is_starter           BOOLEAN      NOT NULL DEFAULT FALSE,
    source               VARCHAR(16),
    plate_appearances    INTEGER      NOT NULL DEFAULT 0,
    at_bats              INTEGER      NOT NULL DEFAULT 0,
    runs                 INTEGER      NOT NULL DEFAULT 0,
    hits                 INTEGER      NOT NULL DEFAULT 0,
    doubles              INTEGER      NOT NULL DEFAULT 0,
    triples              INTEGER      NOT NULL DEFAULT 0,
    home_runs            INTEGER      NOT NULL DEFAULT 0,
    rbi                  INTEGER      NOT NULL DEFAULT 0,
    walks                INTEGER      NOT NULL DEFAULT 0,
    intentional_walks    INTEGER      NOT NULL DEFAULT 0,
    hbp                  INTEGER      NOT NULL DEFAULT 0,
    strikeouts           INTEGER      NOT NULL DEFAULT 0,
    stolen_bases         INTEGER      NOT NULL DEFAULT 0,
    caught_stealing      INTEGER      NOT NULL DEFAULT 0,
    sacrifice_hits       INTEGER      NOT NULL DEFAULT 0,
    sacrifice_flies      INTEGER      NOT NULL DEFAULT 0,
    gdp                  INTEGER      NOT NULL DEFAULT 0,
    avg                  DOUBLE PRECISION,
    obp                  DOUBLE PRECISION,
    slg                  DOUBLE PRECISION,
    ops                  DOUBLE PRECISION,
    iso                  DOUBLE PRECISION,
    babip                DOUBLE PRECISION,
    extra_stats          JSONB,
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    UNIQUE(game_id, player_id)
);

CREATE TABLE IF NOT EXISTS player_game_pitching (
    id                   SERIAL       PRIMARY KEY,
    game_id              VARCHAR(20)  NOT NULL REFERENCES game(game_id) ON DELETE CASCADE,
    player_id            INTEGER      NOT NULL REFERENCES player_basic(player_id) ON DELETE RESTRICT,
    player_name          VARCHAR(64)  NOT NULL,
    team_side            VARCHAR(5)   NOT NULL,
    team_code            VARCHAR(10),
    is_starting          BOOLEAN      NOT NULL DEFAULT FALSE,
    appearance_seq       INTEGER,
    source               VARCHAR(16),
    innings_outs         INTEGER      NOT NULL DEFAULT 0,
    hits_allowed         INTEGER      NOT NULL DEFAULT 0,
    runs_allowed         INTEGER      NOT NULL DEFAULT 0,
    earned_runs          INTEGER      NOT NULL DEFAULT 0,
    home_runs_allowed    INTEGER      NOT NULL DEFAULT 0,
    walks_allowed        INTEGER      NOT NULL DEFAULT 0,
    strikeouts           INTEGER      NOT NULL DEFAULT 0,
    hit_batters          INTEGER      NOT NULL DEFAULT 0,
    wild_pitches         INTEGER      NOT NULL DEFAULT 0,
    balks                INTEGER      NOT NULL DEFAULT 0,
    wins                 INTEGER      NOT NULL DEFAULT 0,
    losses               INTEGER      NOT NULL DEFAULT 0,
    saves                INTEGER      NOT NULL DEFAULT 0,
    holds                INTEGER      NOT NULL DEFAULT 0,
    decision             VARCHAR(2),
    batters_faced        INTEGER      NOT NULL DEFAULT 0,
    era                  DOUBLE PRECISION,
    whip                 DOUBLE PRECISION,
    fip                  DOUBLE PRECISION,
    k_per_nine           DOUBLE PRECISION,
    bb_per_nine          DOUBLE PRECISION,
    kbb                  DOUBLE PRECISION,
    extra_stats          JSONB,
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    UNIQUE(game_id, player_id)
);
