"""constants 모듈."""

from __future__ import annotations

from http import HTTPStatus
from zoneinfo import ZoneInfo

HTTP_OK = HTTPStatus.OK

KST = ZoneInfo("Asia/Seoul")

DATE_STR_LEN = 8

GAME_ID_YEAR_START = 0
GAME_ID_YEAR_END = 4
GAME_ID_YEAR_LEN = 4
GAME_ID_MIN_LEN = 10
GAME_ID_FULL_LEN = 12

KBO_FOUNDING_YEAR = 1982
KBO_EARLY_ERA_END = 1985
KBO_MID_80S_ERA_END = 1988
KBO_MID_90S_ERA_END = 1995
KBO_90S_ERA_END = 1999
KBO_MILLENNIUM_ERA_END = 2000
KBO_2000S_ERA_END = 2001
KBO_PLAYOFF_ERA_END = 2006
KBO_SEMI_PLAYOFF_ERA_END = 2014
KBO_QUALITY_AUDIT_START_YEAR = 2020
KBO_MAX_VALID_SEASON = 2030
KBO_MAX_GAMES_PER_SEASON = 165
KBO_MAX_HOME_RUNS_PER_SEASON = 65
KBO_MAX_WINS_PER_SEASON = 35

MIN_KBO_PLAYER_ID = 10_000

MAX_INNINGS = 9
MAX_OUTS = 3

SURROGATE_PLAYER_ID_BOUNDARY = 900000

BASE_STATE_FIRST = 1
BASE_STATE_SECOND = 2
BASE_STATE_THIRD = 4

IP_FRAC_THIRD = 33
IP_FRAC_TWO_THIRDS = 66
